# You have to configure this ###################################################
title: Web Hated Forkx
# You should configure this ####################################################
url: http://localhost:4000
url: https://mibamur.github.io/Russ/
subtitle: Static Site Podcast Publishing for IT Geeks
description: Iternet Web Hated Forkx.
author: Mikhail
email: it2000@amur.net
keywords: [octopod, podcast, magic]
itunes_categories: [Technology]
# additional_feeds:
#   itunes: http://itunes.apple.com/de/podcast/podcast_name/id42424242
#   torrent_m4a: http://bitlove.org/example_user/example_podcast_m4a/feed
#   torrent_mp3: http://bitlove.org/example_user/example_podcast_mp3/feed
## podlove-web-palyer ##########################################################
poster: /img/logo-360x360.png
alwaysShowHours: true
startVolume: 0.8
width: auto
summaryVisible: true
timecontrolsVisible: true
chaptersVisible: true
sharebuttonsVisible: true
## Rsync Deploy config #########################################################
### Be sure your public key is listed in your server's ~/.ssh/authorized_keys
### file.
ssh_host: user@agrofair.ru
ssh_port: 22
document_root: /var/www/html`
rsync_delete: true
# You can configure this #######################################################
twitter_nick: jekyll_octopod
language: ru
explicit: 'no'  # 'yes'/'no'/clean
license: CC BY 4.0
## Flattr ######################################################################
flattr_uid: # Flattr will not be used unless this is set
flattr_button: compact # compact | default
flattr_mode: auto # auto | manual(default)
flattr_popout:  1 # 1 | 0 (show popout when hovering mouse over button)
flattr_language: en_GB # available languages - https://api.flattr.com/rest/v2/languages.txt
flattr_category: audio # available categories - https://api.flattr.com/rest/v2/categories.txt
## Disqus comments #############################################################
disqus_shortname: # Disqus will not be used unless this is set
disqus_developer: 0 # 1 / 0
## Itunes link ###########################################################
itunes_url: "https://itunes.apple.com/at/podcast/myname/id#myid#"
markdown: kramdown
highlighter: rouge
